apiVersion: v1
kind: Secret
metadata:
  name: kwazo-comment-database
type: Opaque
data:
  MYSQLDB_DATABASE: Y29tbWVudHNlcnZpY2U=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kwazo-comment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kwazo-comment
  template:
    metadata:
      labels:
        app: kwazo-comment
        version: IMAGE_LABEL
    spec:
      containers:
      - name: kwazo-comment
        image: ACR_URL/kwazo-comment:IMAGE_LABEL         
        envFrom:
        - secretRef:
            name: kwazo-comment-database
        - secretRef:
            name: kwazo
        ports:
        - containerPort: 8080
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: kwazo-comment-service
spec:
  ports:
  - port: 80
    name: http
    targetPort: 8080
  selector:
    app: kwazo-comment